#!/bin/bash
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash



xterm -geometry 80x36+0+0 -e "cd bags && taskset -c 6 rosbag record /dji_sdk/attitude /dji_sdk/height_above_takeoff /viral2_odometry/pred_odom /firefly/command/roll_pitch_yawrate_thrust /firefly/command/trajectory_true /dji_sdk/flight_control_setpoint_generic" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch 'roslaunch dji_sdk sdk.launch'" & sleep 1 
#xterm -geometry 80x36+0+0 -e "rosrun cvt_combine_image_into_one cvt_combine_image_into_one_node " & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun stereo_camera_gpu stereo_camera_gpu_node" &  sleep 1
#xterm -hold -geometry 80x36+0+0 -e "echo \' | sudo chmod 666 /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT2QSUMP-if00-port0" & sleep 1
#xterm -hold -geometry 80x36+0+0 -e "roslaunch imu_vn_100 vn_100_cont.launch" & sleep 1
#xterm -hold -geometry 80x36+0+0 -e "rqt_image_view" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch vins_estimator A3.launch" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch '/home/snake/Desktop/octomap_mapping.launch'" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch vins_estimator vins_rviz.launch" & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun dji_sdk_demo demo_flight_control" & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun octomap_server_clear octomap_server_clear" & sleep 1
#xterm -geometry 80x36+0+600 -e "rosrun rqt_reconfigure rqt_reconfigure" &



