#!/bin/bash
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash

# Reduce latency kernel to 1ms
for file in $(ls /sys/bus/usb-serial/devices/); do
  value=`cat /sys/bus/usb-serial/devices/$file/latency_timer`
  if [ $value -gt 1 ]; then
    echo "Setting low_latency mode for $file"
    sudo sh -c "echo 1 > /sys/bus/usb-serial/devices/$file/latency_timer"
  fi
done

#enp2s0  enp3s0 
#Setting up Lidar 1 adapter
sleep 6 #prevent from loading config too fast
#using xterm just incase some script like dnsmasq looping

xterm -hold -geometry 80x36+0+0 -e "nmcli con down lidar2" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -hold -geometry 80x36+0+0 -e "nmcli con down Wired_connection_1" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -hold -geometry 80x36+0+0 -e "nmcli con down Wired_connection_2" & sleep 0.1 #added for flush does not remove existint 
#xterm -geometry 80x36+0+0 -e "nmcli con down ousterLIDAR" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr flush dev enp0s31f6" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr flush dev enp0s31f6" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr show dev enp0s31f6" &  sleep 0.5 
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr add 10.5.5.1/24 dev enp0s31f6" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip link set enp0s31f6 up" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr show dev enp0s31f6" &  sleep 0.5


xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr flush dev enx8cae4ce11af0" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr flush dev enx8cae4ce11af0" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr show dev enx8cae4ce11af0" &  sleep 0.5 
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr add 10.5.6.1/24 dev enx8cae4ce11af0" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip link set enx8cae4ce11af0 up" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S ip addr show dev enx8cae4ce11af0" &  sleep 0.5

xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S dnsmasq -C /dev/null -kd -F 10.5.5.50,10.5.5.100 -i enp0s31f6 --bind-dynamic" & sleep 0.5 
xterm -geometry 80x36+0+0 -e "echo 'dji' | sudo -S dnsmasq -C /dev/null -kd -F 10.5.6.50,10.5.6.100 -i enx8cae4ce11af0 --bind-dynamic" & sleep 20 
killall xterm & sleep 2

#http://os1-991924000164.local/


#Setting up LIDAR2 adapter
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip addr flush dev eno-564774567" & sleep 0.1
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip addr show dev eno-564774567" &  sleep 0.1 
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip addr add 10.5.6.1/24 dev eno-564774567" &  sleep 0.1
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip link set eno-564774567 up" &  sleep 0.1
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip addr show dev eno-564774567" &  sleep 0.1

#Remove notes in the software guide as they are not working for systemd method
#xterm -geometry 80x36+0+0 -e "echo 'uav' | sudo -S ip addr flush dev enp59s0&&echo 'uav' | sudo -S ip addr show dev enp59s0&&echo 'uav' | sudo -S ip addr add 10.5.5.1/24 dev enp59s&&echo 'uav' | sudo -S ip link set enp59s0 up&&echo 'uav' | sudo -S dnsmasq -C /dev/null -kd -F 10.5.5.50,10.5.5.100 -i enp59s0 --bind-dynamic" & sleep 15
#echo 'uav' | sudo -S ip addr flush dev enp59s0&&echo 'uav' | sudo -S ip addr show dev enp59s0&&echo 'uav' | sudo -S ip addr add 10.5.5.1/24 dev enp59s&&echo 'uav' | sudo -S ip link set enp59s0 up 

#xterm -e "roslaunch ouster_ros os1.launch os1_hostname:=os1-991901000605.local os1_udp_dest:=10.5.5.1"  
#xterm -e "roslaunch ouster_ros os1.launch os1_hostname:=os1-991838000392.local os1_udp_dest:=10.5.6.1"  

#xterm -e "roslaunch ouster_ros ouster.launch sensor_hostname:=os1-991901000605.local udp_dest:=10.5.5.1 viz:=true"  
#xterm -e "roslaunch ouster_ros ouster.launch sensor_hostname:=os1-991924000164.local udp_dest:=10.5.6.1 viz:=true" 


#xterm -hold -e "roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991901000605.local os1_hostname2:=os1-991912000362.local os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  
#xterm -hold -e "roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991838000392.local os1_hostname2:=os1-991901000605.local os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  
#xterm -hold -e "roslaunch ouster_ros os1x2.launch os1_hostname:=192.168.2.83 os1_hostname2:=192.168.2.119 os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  



#xterm -hold -e "roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991901000605.local os1_hostname2:=os1-991924000164.local os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  



xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S setserial /dev/serial/by-id/usb-1027_Time_Domain_P440_200-if00 low_latency" & sleep 1
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S setserial /dev/serial/by-id/usb-1027_Time_Domain_P440_200-if00 low_latency" & sleep 1
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S setserial /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT2QSUMP-if00-port0 low_latency" & sleep 1 
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S setserial /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 low_latency" & sleep 1 

xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S chmod a+rw /dev/serial/by-id/usb-1027_Time_Domain_P440_200-if00" & sleep 1
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S chmod a+rw /dev/serial/by-id/usb-1027_Time_Domain_P440_201-if00" & sleep 1 
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S chmod a+rw /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT2QSUMP-if00-port0" & sleep 1 
xterm -geometry 80x36+1000+1000 -e "echo 'dji' | sudo -S chmod a+rw /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0" & sleep 1 


xterm -geometry 80x20+0+890 -e "roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991924000164.local os1_hostname2:=os1-991901000605.local os1_udp_dest:=10.5.6.1 os1_udp_dest2:=10.5.5.1"  & sleep 2 
xterm -geometry 80x20+0+000 -e "taskset -c 1 roslaunch ueye_cam ueye.launch" & sleep 2
xterm -geometry 80x20+0+300 -e "taskset -c 2 roslaunch /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/dji_sdk/launch/sdk.launch" & sleep 1 
xterm -geometry 80x20+0+590 -e "taskset -c 3 roslaunch imu_vn_100 vn_100_cont.launch" & sleep 2


xterm -geometry 80x20+500+000 -e "taskset -c 0 roslaunch uwb_driver uwb0_driver.launch" & sleep 2
xterm -geometry 80x20+500+300 -e "taskset -c 0 roslaunch uwb_driver uwb1_driver.launch" & sleep 2
xterm -geometry 80x20+500+590 -e "taskset -c 0 roslaunch uwb_driver sc_uwb.launch" & sleep 2

xterm -fa 'Monospace' -fs 18 -geometry 80x16+1000+000 -e "rostopic hz /os1_cloud_node1/points /os1_cloud_node2/points /imu/imu /left/image_raw /right/image_raw /uwb_endorange_info" & sleep 2







