#!/bin/bash
source /opt/ros/kinetic/setup.bash
source /home/dji/catkin_ws/devel/setup.bash



#xterm -geometry 80x36+0+400 -e "taskset -c 2 roslaunch /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/dji_sdk/launch/sdk.launch" & sleep 1 
#xterm -geometry 80x36+0+0 -e "rosrun cvt_combine_image_into_one cvt_combine_image_into_one_node " & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun stereo_camera_gpu stereo_camera_gpu_node" &  sleep 1
#xterm -hold -geometry 80x36+0+0 -e "echo \' | sudo chmod 666 /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT2QSUMP-if00-port0" & sleep 1
#xterm -hold -geometry 80x36+0+800 -e "taskset -c 3 roslaunch imu_vn_100 vn_100_cont.launch" & sleep 2
#xterm -hold -geometry 80x36+0+0 -e "rqt_image_view" & sleep 1
#xterm -hold -geometry 80x36+400+800 -e "taskset -c 4-5 roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991901000605.local os1_hostname2:=os1-991924000164.local os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  & sleep 2
#xterm -hold -e "roslaunch ouster_ros os1x2.launch os1_hostname:=os1-991924000164.local os1_hostname2:=os1-991901000605.local os1_udp_dest:=10.5.6.1 os1_udp_dest2:=10.5.5.1"  & sleep 2 

#xterm -geometry 80x16+1000+400 -e "roslaunch ubplanner_bridge fake_odom_dji.launch "  & sleep 3
xterm -hold -geometry 80x16+1000+400 -e "rosrun uwb_driver rnwatch"  & sleep 3 

#xterm -hold -geometry 80x36+400+200 -e "taskset -c 0 roslaunch uwb_driver uwb0_driver.launch" & sleep 2
#xterm -hold -geometry 80x36+600+200 -e "taskset -c 0 roslaunch uwb_driver uwb1_driver.launch" & sleep 2
#xterm -hold -geometry 80x36+800+200 -e "taskset -c 0 roslaunch uwb_driver sc_uwb.launch" & sleep 2
#xterm -hold -geometry 80x36+400+800 -e "roslaunch ouster_ros os1.launch os1_hostname:=os1-991901000605.local os1_hostname2:=os1-991912000362.local os1_udp_dest:=10.5.5.1 os1_udp_dest2:=10.5.6.1"  & sleep 2

#xterm -hold -geometry 80x36+0+0 -e "rosrun camera_calibration cameracalibrator.py --approximate 0.1 --size 8x6 --square 0.108 right:=/right/image_raw left:=/left/image_raw right_camera:=/right left_camera:=/left" & sleep 1
#xterm -hold -geometry 80x36+800+800 -e "source /opt/ros/kinetic/setup.bash && taskset -c 5 rosrun libsensors_monitor libsensors_monitor"


#xterm -geometry 80x36+0+0 -e "roslaunch vins_estimator A3.launch" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch '/home/snake/Desktop/octomap_mapping.launch'" & sleep 1
#xterm -geometry 80x36+0+0 -e "roslaunch vins_estimator vins_rviz.launch" & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun dji_sdk_demo demo_flight_control" & sleep 1
#xterm -geometry 80x36+0+0 -e "rosrun octomap_server_clear octomap_server_clear" & sleep 1
#xterm -geometry 80x36+0+600 -e "rosrun rqt_reconfigure rqt_reconfigure" &


