#!/bin/bash
source /opt/ros/melodic/setup.bash 
source /home/nuc/catkin_driver_ws/devel/setup.bash





#sudo apt-get install libglew-dev

#enp2s0  enp3s0 
#Setting up Lidar 1 adapter
sleep 6 #prevent from loading config too fast
#using xterm just incase some script like dnsmasq looping


#xterm -e "echo 'nuc' | sudo -S  ptp4l -i eno1 -l 6 -m" & sleep 1 
#xterm -e "echo 'nuc' | sudo -S  phc2sys -c eno1 -s CLOCK_REALTIME -O 0" & sleep 1 


#xterm -hold -geometry 80x36+0+0 -e "nmcli con down static" & sleep 0.1 #added for flush does not remove existint connection directly
#xterm -geometry 80x36+0+0 -e "nmcli con down static" & sleep 0.1 #added for flush does not remove existint connection directly
#xterm -geometry 80x36+0+0 -e "nmcli dev disconnect eno1" & sleep 0.1 #added for flush does not remove existint connection directly

#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip addr flush dev eno1" & sleep 0.5
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip addr flush dev eno1" & sleep 0.5
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip addr show dev eno1" &  sleep 0.5 
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip addr add 192.168.1.50/24 dev eno1" &  sleep 0.5
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip link set eno1 up" &  sleep 0.5
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S ip addr show dev eno1" &  sleep 0.5


#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S dnsmasq -C /dev/null -kd -F 10.5.5.50,10.5.5.100 -i eno1 --bind-dynamic" & sleep 20
#xterm -geometry 80x36+0+0 -e "echo 'nuc' | sudo -S dnsmasq -C /dev/null -kd -F 192.168.1.50,192.168.1.100 -i eno1 --bind-dynamic" & sleep 20

#killall xterm

#xterm -e "roslaunch ouster_ros ouster.launch sensor_hostname:=os-122121000609.local udp_dest:=192.168.1.50 viz:=true" & sleep 1 


#prep serial device
#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S setserial /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT40AOE1-if00-port0 low_latency" & sleep 1 
#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S chmod a+rw /dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT40AOE1-if00-port0" & sleep 1 


#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S setserial /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_12c03c067c73ea11aa3b0e13cf25bb41-if00-port0 low_latency" & sleep 1 
#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S chmod a+rw /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_12c03c067c73ea11aa3b0e13cf25bb41-if00-port0" & sleep 1 

#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S setserial /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_9c310e3f9473ea11b39d492acf25bb41-if00-port0 low_latency" & sleep 1 
#xterm -geometry 80x36+1000+1000 -e "echo 'nuc' | sudo -S chmod a+rw /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_9c310e3f9473ea11b39d492acf25bb41-if00-port0" & sleep 1 


#xterm -geometry 80x20+0+300 -e "roslaunch realsense2_camera rs_camera_D435.launch" & sleep 4 
#xterm -geometry 80x20+0+300 -e "roslaunch realsense2_camera rs_camera_D455_0.launch" & sleep 6
#xterm -geometry 80x20+0+600 -e "roslaunch realsense2_camera rs_camera_D455_1.launch" & sleep 6



#xterm -geometry 80x20+0+590 -e "roslaunch imu_vn_100 vn_100_cont.launch" & sleep 2
#xterm -geometry 80x20+0+590 -e "roslaunch vectornav vectornav_vn200.launch" & sleep 2

# Launch the livox
xterm -geometry 80x20+0+430 -e "roslaunch livox_ros_driver livox_lidar_msg.launch bd_list:='3GGDJ5S0010017'" & sleep 2
# Adjust the rviz window
(sleep 5; wmctrl -r 'display_lidar_points.rviz - RViz' -e '0,1045,361,884,757')

# Launch the dji osdk
xterm -geometry 80x20+0+720 -e "roslaunch dji_osdk_ros dji_vehicle_node.launch" & sleep 2
# Call the camera service
(sleep 10; rosservice call /stereo_vga_subscription '{vga_freq: 0, front_vga: 1, unsubscribe_vga: 0}') & sleep 2



#xterm -geometry 80x20+0+590 -e "source ~/dev_ws/devel/setup.bash && roslaunch nlink_parser linktrack_atv.launch" & sleep 2

xterm -fa 'Monospace' -fs 18 -geometry 98x08+610+0 -e "rostopic hz /dji_osdk_ros/stereo_vga_front_left_images /dji_osdk_ros/stereo_vga_front_right_images /dji_osdk_ros/imu /livox/lidar" & sleep 2
# (sleep 5; wmctrl -r 'lidar' -e '0,568,95,1362,236')

# Launch and position the window
xterm -fa 'Monospace' -fs 18 -geometry 5x5+0+0 -e "rqt_image_view" & sleep 2
(sleep 5; wmctrl -r 'rqt_image_view__ImageView - rqt' -e '0,561,362,485,756')
