#!/bin/bash
source /opt/ros/melodic/setup.bash 
source /home/nuc/catkin_driver_ws/devel/setup.bash


# Launch the livox
xterm -geometry 80x20+0+430 -e "roslaunch livox_ros_driver livox_lidar_msg.launch bd_list:='3GGDJ5S0010017'" & sleep 2
# Adjust the rviz window
(sleep 5; wmctrl -r 'display_lidar_points.rviz - RViz' -e '0,1045,361,884,757')

# Launch the dji osdk
xterm -geometry 80x20+0+720 -e "roslaunch dji_osdk_ros dji_vehicle_node.launch" & sleep 2
# Call the camera service
(sleep 10; rosservice call /stereo_vga_subscription '{vga_freq: 0, front_vga: 1, unsubscribe_vga: 0}') & sleep 2


#xterm -geometry 80x20+0+590 -e "source ~/dev_ws/devel/setup.bash && roslaunch nlink_parser linktrack_atv.launch" & sleep 2

xterm -T "Subscribed topics" -fa 'Monospace' -fs 18 -geometry 98x08+610+0 -e "rostopic hz /dji_osdk_ros/stereo_vga_front_left_images /dji_osdk_ros/stereo_vga_front_right_images /dji_osdk_ros/imu /livox/lidar" & sleep 2
(sleep 5; wmctrl -r 'Subscribed topics' -e '0,568,0,1362,236')

# Launch and position the window
xterm -T "rqt_image_view xterm" -fa 'Monospace' -fs 18 -geometry 5x5+0+0 -e "rqt_image_view" & sleep 2
(sleep 5; wmctrl -r 'rqt_image_view__ImageView - rqt' -e '0,561,362,485,756' \
       && wmctrl -r 'rqt_image_view xterm' -e '0,68,1080,172,05')
