#!/bin/bash
source /opt/ros/melodic/setup.bash 
source /home/nuc/catkin_driver_ws/devel/setup.bash

LOG_DIR=/home/nuc/bags

xterm -geometry 80x8+0+600 -e "cd $LOG_DIR && roslaunch ~/Desktop/script/rosbag.launch & (sleep 3; watch -n 1 'du -skh $LOG_DIR')" & sleep 1
watch -n 1 "du -skh $LOG_DIR" # Monitor the size of the folder

