#!/bin/bash
source /opt/ros/melodic/setup.bash 
source /home/nuc/catkin_driver_ws/devel/setup.bash

# Reduce latency kernel to 1ms
# for file in $(ls /sys/bus/usb-serial/devices/); do
#   value=`cat /sys/bus/usb-serial/devices/$file/latency_timer`
#   if [ $value -gt 1 ]; then
#     echo "Setting low_latency mode for $file"
#     sudo sh -c "echo 1 > /sys/bus/usb-serial/devices/$file/latency_timer"
#   fi
# done

# Launch the vn200 imiu
xterm -T "Launch IMU" -geometry 80x15+0+0 -e "roslaunch vectornav vectornav.launch" & sleep 2

# Launch the ouster
xterm -T "Launch Ouster" -geometry 80x15+0+150 -e "roslaunch ouster_ros ouster.launch " & sleep 2

# Launch the livox, which has the rviz
xterm -T "Launch Livox" -geometry 80x15+0+250 -e "roslaunch livox_ros_driver livox_lidar_msg.launch bd_list:='3GGDJ5S0010017'" & sleep 2
# Adjust the rviz window
(sleep 3; wmctrl -r 'display_lidar_points.rviz - RViz'  -e '0,1045,361,1369,757') #Adjust the position of rviz
(sleep 3; wmctrl -r 'display_lidar_points.rviz* - RViz' -e '0,1045,361,1369,757') #Adjust the position of rviz

# Launch the realsense camera
xterm -T "Launch D455" -geometry 80x15+0+350 -e "roslaunch realsense2_camera rs_camera_D455_0.launch & roslaunch realsense2_camera rs_camera_D455_1.launch" & sleep 2
# xterm -T "Launch D455 cam1" -geometry 80x15+0+450 -e "roslaunch realsense2_camera rs_camera_D455_1.launch" & sleep 2

#xterm -geometry 80x20+0+590 -e "source ~/dev_ws/devel/setup.bash && roslaunch nlink_parser linktrack_atv.launch" & sleep 2

# # Launch the pylon camera node
# xterm -T "Launch OSDK" -geometry 80x20+0+320 -e "roslaunch pylon_camera pylon_camera_node.launch" & sleep 2

# Inspect the rates
xterm -T "Subscribed topics" -fa 'Monospace' -fs 18 -geometry 98x08+610+0 -e \
"rostopic hz /livox/lidar /vectornav/IMU /os_cloud_node/imu /os_cloud_node/points /rsD455_node0/color/image_raw /rsD455_node1/color/image_raw" & sleep 2
(sleep 3; wmctrl -r 'Subscribed topics' -e '0,568,0,1362,236') #Adjust the window for subscription status

# Launch and position the window
# xterm -T "rqt_image_view xterm" -fa 'Monospace' -fs 18 -geometry 5x5+0+0 -e "rqt_image_view /dji_osdk_ros/stereo_vga_front_right_images" & sleep 2
# (sleep 3; wmctrl -r 'rqt_image_view__ImageView - rqt' -e '0,561,362,485,756' \
#        & wmctrl -r 'rqt_image_view xterm' -e '0,68,1080,172,05') #Adjust the rqt view
